name: SimpleMarkdown
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - magic_pdf>=1.0.0
    - python-dotenv>=0.19.0
    - argparse>=1.4.0
    - pathlib>=1.0.0
    - huggingface_hub>=0.16.0 